### ISSUE TITLE
Error: The operation couldn’t be completed. (JSONUtilities.DecodingError error 0.)

### ISSUE THREAD

**Issue by gali8** [yonaskolb/SwagGen#1]
Using
./SwagGen --template Templates/Swift --spec ~/Desktop/File.json

i'm obtaining the error
Error: The operation couldn’t be completed. (JSONUtilities.DecodingError error 0.)

What's wrong?

**Comment by yonaskolb** [comment]
Could you post your spec file?

**Comment by yonaskolb** [comment]
I've improved the error handling, and also made a lot more things in the swagger spec optional, as it was expecting certain properties that may not be there in a still valid spec, which is what I think the problem was. Let me know how you go now

**Comment by yonaskolb** [comment]
Hi @gali8, I'm closing this now. Your problem should be fixed. Let me know if you have any other issues
