### ISSUE TITLE
Malformed operationId

### ISSUE THREAD

**Issue by HSchultjan** [yonaskolb/SwagGen#10]
When generating code for `https://api.closely.io/v1/location/swagger.json` the operationId is generated malformed for several requests.

## Example:
`PUT` request for the resource `http://host/v1/location/{project}/devices/{device}"`

Expected operationId:
`putV1LocationByProjectByDevices`

Actual operationId:
`putV1LocationByProject}Devices{device`

**Comment by HSchultjan** [comment]
Turns out the Regex for generating the operationId was too greedy.

**Comment by yonaskolb** [comment]
Thanks for fixing that @HSchultjan. Yeah it's best if specs actually define the operationId, as the generated ones can be a bit ugly.

It also seems that repo would also require #6 to be completed to be able to generate properly

**Comment by yonaskolb** [comment]
@HSchultjan #6 has now been implemented, so this spec should generate now. It's not a very well defined one as all schema properties seem to be optional
