### ISSUE TITLE
Ignores top-level "security" definition

### ISSUE THREAD

**Issue by KingMob** [yonaskolb/SwagGen#102]
In the [OpenAPI 2.0 definition of top-level fields](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields), in the "security" row, it says it is:

> A declaration of which security schemes are applied for the API as a **whole**. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). Individual operations can override this definition. [Emphasis mine]

Right now, it appears as if SwagGen only sets Authorizations for Requests that have their own *individual* `security` field set, but ignores the global `security` field.

**Comment by yonaskolb** [comment]
Hi @KingMob.
Yes you're correct, at the moment the top level `security` schemes are not supported (though they should be easy to add)

**Comment by KingMob** [comment]
Thanks @yonaskolb. Was that documented somewhere?

**Comment by yonaskolb** [comment]
Unfortunately not

**Comment by yonaskolb** [comment]
@KingMob resolved in #104

**Comment by yonaskolb** [comment]
Be aware that post https://github.com/yonaskolb/SwagGen/pull/103, `authorization` has been renamed `securityRequirement` in the inbuilt swift template
