### ISSUE TITLE
Thread 1: Fatal error: Index out of range on RequestBehaviour line 70

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/SwagGen#105]
In the new version 3.0 we are obligated to have a `behaviours` on request or it crash.

**Comment by yonaskolb** [comment]
Thanks fore reporting @mackoj.
Fixed by #108 

Please let me know if you have any other issues in 3.0 so we can get them fixed

**Comment by mackoj** [comment]
Thanks for the fix
