### ISSUE TITLE
How to make `$ref` model conform to a protocol ?

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/SwagGen#107]
How can I make models that will be use in response(`$ref`) conform to a particular protocol ?

```yaml
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/user'
```

```swift

public protocol BaseModel {
  var code: String? { set get }
  var msg: String? { set get }
  var token: String? { set get }
}

```
The protocol conformance in question don't require adding code but only adding the conformance all the work is done in the protocol itself.

In this case I want to make the `User` conform to `BaseModel` because all object that is in response always conform to `BaseModel`.

Thanks,

**Comment by yonaskolb** [comment]
All models now conform to `APIModel` which you could add your extensions to #109

**Comment by mackoj** [comment]
Thanks, again for this feature.
