### ISSUE TITLE
How can I namespace models ?

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/SwagGen#110]
Hi @yonaskolb,

The swagger file that I work with has multiple models with the same name on different endpoint which results in model rewriting themselves randomly when I update them.

How can I namespace my model with the same namespace that request have?

Thanks,

**Comment by yonaskolb** [comment]
Hi @mackoj, not sure I understand. If the models are listed in definitions then they will all be sharing the exact same model. If the models are inline as a schema they should be generated within the request.
Are these request or response models? Do you have an example?

**Comment by mackoj** [comment]
After further research it's my be illegal to do what I explain above.
But when I process this [swagger file](https://gist.github.com/mackoj/47c4519839ac317a13d0c26909e15177) with swaggen it shows two `Categorie`,  `Item`, `URL`, `Lien`, `Menu`, `Rdv` for exemple on the readme as if there is two versions of them.

**Comment by mackoj** [comment]
I think the swagger file is really wrong don't bother.
