### ISSUE TITLE
Warning in Coding.swift

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/SwagGen#126]
Can I submit a PR for fixing these ?

```
    - WARN  | [iOS] xcodebuild:  /XXXX//Coding.swift:262:117: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
    - NOTE  | [iOS] xcodebuild:  /XXXX//Coding.swift:262:141: note: use 'String(describing:)' to silence this warning
    - NOTE  | [iOS] xcodebuild:  /XXXX//Coding.swift:262:141: note: provide a default value to avoid this warning
```

**Comment by yonaskolb** [comment]
I believe this is fixed in master.
Master actually has quite a lot of changes so it might be worth checking that out. Note though that it's Swagger 3 only.

But in general feel free to open any PRs 😄👍

**Comment by mackoj** [comment]
I can't try it for the moment because our swagger file is in swagger 2 format. I will work with the backend team to migrate to swagger 3 format and try.
