### ISSUE TITLE
descriminator -> discriminator

### ISSUE THREAD

**Issue by cooksimo** [yonaskolb/SwagGen#129]
According to the docs: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject this is misspelled currently.

**Comment by yonaskolb** [comment]
Yes, you're right. Where are you seeing this? Feel free to open a PR

**Comment by yonaskolb** [comment]
Fixed some cases I found in the code https://github.com/yonaskolb/SwagGen/commit/1eddb0196dd6b7e057623399de8f614dbc514651
