### ISSUE TITLE
Getting `Reference ... is unresolved` when generating from OAS3

### ISSUE THREAD

**Issue by Kastet** [yonaskolb/SwagGen#131]
Hi,

I was wondering if OAS3 was supported and gave it a go.

I used code from master, passed [this spec](https://github.com/yonaskolb/SwagGen/files/2982509/api-schema.json.zip) as a launch argument. 
Getting `Thread 1: Fatal error: Reference #/components/schemas/User is unresolved`

Not sure if it's a bug or something isn't supported yet.

**Comment by yonaskolb** [comment]
Thanks for the report @Kastet. I've fixed the unresolved component here https://github.com/yonaskolb/SwagGen/pull/132

That spec still won't generate properly though, as an object schema can't be used as a path parameter. Would does the api expect to send? Just a simple string, or the whole user object encoded in some form?

**Comment by Kastet** [comment]
Hi @yonaskolb ,

Thanks for looking into this. Agree that passing a complex object as a path param doesn't make sense.

However, `$ref` isn't necessarily an object schema, it can be just a type alias, for example 

```
"UUID": {
        "type": "string"
      }
```

Would it make sense to allow `$ref` as path param provided its type is a primitive?

**Comment by yonaskolb** [comment]
Yeah that should work fine. The reference isn’t the problem (anymore) it’s that the schema type is an object

**Comment by Kastet** [comment]
Awesome!

Just tested and found one minor problem. The `UUID` schema resolves into a type alias `public typealias UUID = String` which exactly what I'd expect, but it collides with Foundation's UUID extension in Coding.swift
```
extension UUID {
    func encode() -> Any {
        return uuidString
    }
}
```

A simple fix would be changing the template to

```
extension Foundation.UUID {
    func encode() -> Any {
        return uuidString
    }
}
```

Thoughts @yonaskolb ?

**Comment by yonaskolb** [comment]
Hmm, I'm not seeing this. There is a template option to map what `ID` is generated as (typeAliases.ID). It defaults to `UUID`
In `Coding.swift` this is then generated as `public typealias ID = UUID`.
Are you using the latest release, and the included template?

**Comment by Kastet** [comment]
Yep, using 4.0.0. 
![image](https://user-images.githubusercontent.com/611542/54662794-51d77200-4b33-11e9-9b43-de60ce6da205.png)

**Comment by yonaskolb** [comment]
And where are you getting the `public typealias UUID = String` from?

**Comment by Kastet** [comment]
It's a model that gets generated from my a schema, to illustrate
```
"components": {
    "schemas": {
      "UUID": {
           "type": "string"
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "$ref": "#/components/schemas/UUID"
          },
         .....
    }
}
```

**Comment by yonaskolb** [comment]
Oh I see, you have a custom schema that conflicts with Foundation. I would suggest using swaggers inbuilt `format: uuid` instead of a custom `UUID` schema (SwagGen will generate this as an `ID` typealias, which you can change what that resolves to in the template options). Alternatively you can update the template with your Foundation suggestion, but you'll continue to get clashes throughout your codebase.
Either way happy for you to create a PR to add the `Foundation.UUID`
