### ISSUE TITLE
XCTest support

### ISSUE THREAD

**Issue by Kastet** [yonaskolb/SwagGen#138]
Is XCTest supported? I tried Cmd+U and was getting 
```
Fatal error: Use of global context is not permitted when running inside XCTest
```

**Comment by yonaskolb** [comment]
Hi @Kastet. Could you give some more information. 

Do you mean the SwagGen codebase? If so and you've created an xcode project with `swift package generate-xcodeproj`, then yes just select the SwagGen scheme and press Cmd+U.

If you mean the generated Swift API then it totally depends on how you integrate it into your codebase. The generated code doesn't include any tests

**Comment by yonaskolb** [comment]
Wait I just tried running the tests via Xcode in SwagGen and I can see your issue. This is an integration issue with the test runner Spectre, and needs to be fixed 👍 

In the meantime if you want to run the tests you can run `swift test` in the repo directory

**Comment by Kastet** [comment]
Thanks @yonaskolb and apologies for the poor description.

Yes I ended up running tests using SPM. It's the first time I used it - pretty cool.

**Comment by yonaskolb** [comment]
Strange, I went to fix this but found it isn't an issue anymore. Perhaps the update to Xcode 10.2 fixed something

**Comment by Kastet** [comment]
Just tried with Xcode10.2 and still able to reproduce 
<img width="1790" alt="Screen Shot 2019-04-10 at 4 48 04 pm" src="https://user-images.githubusercontent.com/611542/55857432-81b4eb00-5bb0-11e9-8990-9d14e9c4b2bd.png">
