### ISSUE TITLE
additionalProperties support

### ISSUE THREAD

**Issue by wuf810** [yonaskolb/SwagGen#14]
Needs support for additionalProperties (part of the OpenAPI specification). The official Swagger Codegen for Swift has some support for additionalProperties but would be great to see the same support in this project (as the code generated is so much nicer).

NB additionalProperties need to be supported in many cases:

1. Classes with no static properties but additionalProperties
2. Classes with both static and additionalProperties
3. Classes that are inheriting from classes with additionalProperties and vice versa.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject

**Comment by yonaskolb** [comment]
Yes, I believe SwagGen only supports the first case you mention, which doesn't generated a class but rather a dictionary such as [String: Model] or [String: Int] (or any other simple type).
Do you have a link or snippet of a spec that you would like to support?

**Comment by wuf810** [comment]
Hi @yonaskolb 

Yeh the implementation in Swagger codeGen was completely broken as someone tried to implement it like java and of course in Swift the class cannot just be a subclass of the dictionary (unless they changed the class's base type to an NSDictionary but that's not very swift).

@dwoodel and I implemented a solution based on adding an additionalProperties as a collection to the class and using a subscript accessor to set and get the values:

https://github.com/swagger-api/swagger-codegen/pull/5406

Not sure if there is a better approach. What do you think?

Either way I would just love to see it implemented in your generator. I'm happy to help but not 100% sure where to start. any thoughts?

**Comment by yonaskolb** [comment]
Seems a reasonable approach. In my experience additionalProperties are either specified as a property, or as a seperate property of a Definition, not both within one schema. But I guess there are some api's that are defined like that. 
Do you have a spec I could use for testing? Otherwise I'll just create one, and have a stab at this

**Comment by wuf810** [comment]
This is a cut down version of some of the objects we create. Couple with defined properties and additionalProperties and one with just additionalProperties. Hope this helps:

`"UserRequest": {
			"type": "object",
			"description": "Request user model",
			"additionalProperties": {
				"type": "string"
			}
		},
		"UserResponse": {
			"type": "object",
			"properties": {
				"username": {
					"type": "string",
					"example": "jdoe",
					"description": "Name of user"
				},
				"phoneNumber": {
					"type": "string",
					"example": "+375291112233",
					"description": "User's phone number"
				},
				"status": {
					"type": "string",
					"example": "REGISTERED",
					"description": "User's status"
				}
			},
			"description": "Response user model",
			"additionalProperties": {
				"type": "string"
			}
		},
		"CreateUserRequest": {
			"type": "object",
			"properties": {
				"phoneNumber": {
					"type": "string",
					"example": "+375291112233",
					"description": "User's phone number"
				}
			},
			"additionalProperties": {
				"type": "string"
			}
		}`

**Comment by yonaskolb** [comment]
@wuf810 please checkout #15 and see if it fixes your issue
