### ISSUE TITLE
Install version 3.0.2 via homebrew

### ISSUE THREAD

**Issue by StasanTelnov** [yonaskolb/SwagGen#144]
Hello.
I need support swagger version 2.
I try install (macOS):
`brew tap yonaskolb/SwagGen https://github.com/yonaskolb/SwagGen.git/tree/swagger_2
brew install SwagGen`
But installed SwagGen 4.0.0: https://github.com/yonaskolb/SwagGen/archive/4.0.0.tar.gz

How I can install SwagGen 3.0.2 version for support swagger 2?

**Comment by yonaskolb** [comment]
Hi @StasanTelnov 
You should be able to run the following:

```
git clone -b swagger_2 https://github.com/yonaskolb/SwagGen.git
cd SwagGen
make install
```

Homebrew is not good at installing old versions

**Comment by StasanTelnov** [comment]
Yes, I went this way, but hoped that install via homebrew possible too.
Thanks for your answer

**Comment by yonaskolb** [comment]
I can also recommend Mint 😄 https://github.com/yonaskolb/Mint

```
mint install yonaskolb/swaggen@swagger_2
```

**Comment by Alexsays** [comment]
Hi @yonaskolb , I've tried this three methods to install _version 3.0.2_:

1. **Clone repo** and then `make install`.
2. **Clone repo** and tried to execute it with `swift run`.
3. `brew install https://raw.githubusercontent.com/yonaskolb/SwagGen/swagger_2/Formula/SwagGen.rb`.
4. Install **mint** and after that `mint install yonaskolb/swaggen@swagger_2`.

For all of the options I'm getting an issue with **Stencil** and **JSONUtilities** when trying to resolve dependencies. I've tried changing the **Package.swift** file but no luck with it.

> error: dependency graph is unresolvable; found these conflicting requirements:
> Dependencies:
>    https://github.com/yonaskolb/Stencil.git @ 0.9.0..<1.0.0
>    https://github.com/yonaskolb/JSONUtilities.git @ 3.3.0..<4.0.0

**Comment by kubacizek** [comment]
Same error with **Stencil** and **JSONUtilities**.

**Comment by TiagoLira** [comment]
I have the same issue, couldn't find a way to run version 2
