### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by vialyx** [yonaskolb/SwagGen#154]

**Comment by yonaskolb** [comment]
Could you give some more information? Do you mean SwagGen itself or the generated template? Both should support Swift 5 in the latest version

**Comment by Unihilator** [comment]
Hi @yonaskolb ! Nice to meet you. Maybe it's related to swift package manager ver. 5. The thing is I'm getting error when I'm trying to install Swaggen version 3.0.2 and lower. Here what I'm getting:

> error: dependency graph is unresolvable; found these conflicting requirements:

> Dependencies: 
 
>    https://github.com/yonaskolb/Stencil.git @ 0.9.0..<1.0.0
>    https://github.com/yonaskolb/JSONUtilities.git @ 3.3.0..<4.0.0
>🌱  Encountered error during "swift package resolve". Use --verbose to see full output
>🌱  Failed to resolve Swaggen 3.0.2 with SPM

Swift package version gives me Swift 5.0.0 (swiftpm-14490.62.2). I suppose this issue related to SPM 5 because my colleague have Swift 4.2.0 (swiftpm-14460.2) and it's ok with this version

**Comment by yonaskolb** [comment]
Yes SwagGen versions below 4.1.0 aren't compatible with Swift 5. If you're stuck on Swagger 2, I would accept a PR to upgrade the `swagger_2` branch to Swift 5 and we can do a SwagGen 3.1 release.
Is that what you meant as well @vialyx?

**Comment by Unihilator** [comment]
Thanks, will try to contribute)

**Comment by haemi** [comment]
Hi, I'm on SwagGen 4.1.0 - but it generates a podspec with Result as dependency in it; that shouldn't be necessary anymore, right?

**Comment by yonaskolb** [comment]
@haemi, no, master has result removed. I’ll do another release hopefully tonight

**Comment by haemi** [comment]
@yonaskolb when I generate swaggen via cloning the repo and the Xcode project, everything works as expected. But installing 4.1.0 via homebrew includes the Result.

**Comment by yonaskolb** [comment]
4.2.0 released which removes result. Closing this for now
