### ISSUE TITLE
Support for allOf

### ISSUE THREAD

**Issue by kroegerama** [yonaskolb/SwagGen#170]
Is there any support for `allOf` planned? The generated code for `PushPaginated` does not correctly inherit from the referenced types.

```yaml
Pagination:
      type: object
      properties:
        draw:
          type: integer
        recordsTotal:
          type: integer
          format: int64
        recordsFiltered:
          type: integer
          format: int64
        error:
          type: string
      required:
        - draw
        - recordsTotal
        - recordsFiltered
PushItem:
      type: object
      properties:
        title:
          type: string
        subtitle:
          type: string
        content:
          type: string
PushPaginated:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/PushItem'
```

**Comment by yonaskolb** [comment]
Hi @kroegerama. 
allOf is supported. In your case just remove the `type: object` from `PushPaginated` and it should work. Let me know how you go

**Comment by kroegerama** [comment]
Thank you so much! Works fine now :)

**Comment by haemi** [comment]
but does this also work with structs? Inheritance is not possible there... 

And what happens for something like this?

```
SomethingAndSomethingelse:
     allOf:
     - $ref: ‘#/components/schemas/Something’
     - $ref: ‘#/components/schemas/SomethingElse’
```

multiple inheritance is even less possible...

**Comment by yonaskolb** [comment]
Structs will get the properties of both

**Comment by haemi** [comment]
currently I get

```
public struct SomethingAndSomethingelse: Something {
```

with the error `Inheritance from non-protocol type 'Something'`

**Comment by yonaskolb** [comment]
Have you set the template property modelInheritance to false and the modelType to struct?

**Comment by haemi** [comment]
yes; with `modelInheritance` false it works, but only the first reference is used, the `SomethingElse` is ignored...
