### ISSUE TITLE
Error super.init with Multiple inheritance

### ISSUE THREAD

**Issue by julien-h-webcenter** [yonaskolb/SwagGen#173]
Hi,

i contact you because i would like to know if someone have the same problem that me.
When i try to generate my swift classes, the super.init with two or more levels of inheritance doesn't work.

the super.init() of childs have not the parameters of all parents.
i try to explain :

A -> B: A -> C: B
B have all parameters for init include A properties
C have parameters of B but havent  parameters in init for the properties of A.

<img width="1066" alt="Capture d’écran, le 2019-07-02 à 14 51 16" src="https://user-images.githubusercontent.com/17987431/60538660-00fe1a80-9cd9-11e9-9c5f-42c2376a186f.png">

can we modify the generator to fix this problem ?

Thanks.

Julien

**Comment by yonaskolb** [comment]
Yes, modifying the `model.stencil` class to use `allProperties` should work. Would you like to create a PR? Would be great to have an example case in https://github.com/yonaskolb/SwagGen/blob/master/Specs/TestSpec/spec.yml as well

**Comment by julien-h-webcenter** [comment]
I already have fix the problem. i create the PR.
