### ISSUE TITLE
`integer` formats are not taken into account

### ISSUE THREAD

**Issue by jrcmramos** [yonaskolb/SwagGen#176]
### Description
As described in the Swagger/OpenAPI specification (https://swagger.io/docs/specification/data-models/data-types/) data type Integer might have different formats. In this case, these formats can be either `int32` or `int64`.

As far as I am concerned these formats are not taken into account. Is there something that I am missing or reason for this behaviour?

Thank you

**Comment by yonaskolb** [comment]
There is an option in the template called `fixedWidthIntegers` which you can set to true. This will then use Int32 and Int64. You can do this either by modifying the template.yml file or passing it via the command line: `-- option fixedWidthIntegers:true`

**Comment by jrcmramos** [comment]
The `--option fixedWidthIntegers:true` solved the issue 💪 
Thanks @yonaskolb!
