### ISSUE TITLE
Error loading Swagger Spec: Decoding failed at "components": Nothing found

### ISSUE THREAD

**Issue by haemi** [yonaskolb/SwagGen#179]
Some files give me the error `Error loading Swagger Spec: Decoding failed at "components": Nothing found` when trying to generate Swift with SwagGen.

One of those files is this: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml

**Comment by yonaskolb** [comment]
Looks like `components` is required by the decoder, which it technically doesn’t need to be. Most specs will have components but it shouldn’t fail if they don’t

**Comment by haemi** [comment]
thanks for your quick response!

Absolutely not to blame you, but does this mean it's a bug in swaggen? If yes, do you plan to work on it?
