### ISSUE TITLE
Wrong replacing string in variable server

### ISSUE THREAD

**Issue by ymhuang0808** [yonaskolb/SwagGen#208]
OpenAPI/Swagger provides Variable Server/Server Templating. In SwagGen, it also provides [the feature](https://github.com/yonaskolb/SwagGen/blob/1b6a42cf3a4c1eb996d483a2f7394cf88f3de397/Templates/Swift/Sources/API.swift#L39). However, I found the replacing string may be wrong. Therefore, I would like to make sure that if it replaces the URL string with _"variable value"_, instead of _"variable name"_

### Actual

The [line of code]((https://github.com/yonaskolb/SwagGen/blob/1b6a42cf3a4c1eb996d483a2f7394cf88f3de397/Templates/Swift/Sources/API.swift#L39)) is:
```
url = url.replacingOccurrences(of: "{\({{variable.name}})}", with: {{variable.name}})
```

The generated code is:
```
public static func test(space: String = "main", version: String = "v1") -> String {
    var url = "https://test.petstore.com/{version}/{space}"
    url = url.replacingOccurrences(of: "{\(space)}", with: space)
    url = url.replacingOccurrences(of: "{\(version)}", with: version)
    return url
}
```

### Expected

The line of code should look like:
```
url = url.replacingOccurrences(of: "{{{variable.name}}}", with: {{variable.name}})
```

The generated code should be: 
```
public static func test(space: String = "main", version: String = "v1") -> String {
    var url = "https://test.petstore.com/{version}/{space}"
    url = url.replacingOccurrences(of: "{space}", with: space)
    url = url.replacingOccurrences(of: "{version}", with: version)
    return url
}
```

**Comment by ymhuang0808** [comment]
If the issue is confirmed, my teammate @marcuswu0814 would like to contribute it.

**Comment by yonaskolb** [comment]
Yes, good catch! Feel free to submit a PR!

**Comment by marcuswu0814** [comment]
Hi @yonaskolb, currently I faced some problem when using Stencil, is it possible to escape `{` and `}` in this case:

```swift
// Stencil file
url = url.replacingOccurrences(of: "{{{variable.name}}}", with: {{variable.name}})
```

expected:
```
url = url.replacingOccurrences(of: "{version}", with: {{variable.name}})
```

Actual:
```
url = url.replacingOccurrences(of: "", with: {{variable.name}})
```

I can't found any document of escape character in [Stencil web](http://stencil.fuller.li/en/latest/builtins.html#).

**Comment by yonaskolb** [comment]
Yeah I've had this issue in the past. I've solved it before by doing something like this
```
"{" + "{{variable.name}}" + "}"
```

**Comment by marcuswu0814** [comment]
Hi @yonaskolb, thanks for your suggestion, the [PR](https://github.com/yonaskolb/SwagGen/pull/209) is done. 🚀
