### ISSUE TITLE
Missing support using Multiple Authentication Types

### ISSUE THREAD

**Issue by malteburkert** [yonaskolb/SwagGen#214]
According to https://swagger.io/docs/specification/authentication it is possible to specify multiple authentication types for operations. The SwagGen tool seems to not support this requirement. The APIService cannot be initiated with multiple securityRequirements. And it is even not possible to modify the template in order to support this feature. Could you please help with this inquiry?

**Comment by yonaskolb** [comment]
If you need this you can indeed update the template. In addition to the `securityRequirement` property in the `Request.swift` template, you can use the plural `securityRequirements` which is an array. 

If you do make such updates to the template, I'm happy to accept a PR that supports multiple

**Comment by malteburkert** [comment]
@yonaskolb is it possible that the parsing of the swagger spec does not support the AND of multiple securityRequirements?

**Comment by yonaskolb** [comment]
@malteburkert not sure what you mean?
