### ISSUE TITLE
Cannot generate Endpoint if Swagger Spec doesn't have any tag

### ISSUE THREAD

**Issue by dangthaison91** [yonaskolb/SwagGen#24]
template.yml
```ruby
- path: request.swift
  context: tags
```

If Swagger Spec doesn't define any tag, SwagGen couldn't generate API Endpoint with above configuration.

- Actual implementation: Return empty dictionary when tags is empty:
```Ruby
    public var opererationsByTag: [String: [Operation]] {
        var dictionary: [String: [Operation]] = [:]

        for tag in tags {
            dictionary[tag] = operations.filter { $0.tags.contains(tag) }
        }
        return dictionary
}
```
- Expected: Return Dictionary with all Operations for 1 default key:
```Ruby
    public var opererationsByTag: [String: [Operation]] {
        var dictionary: [String: [Operation]] = [:]

        if tags.isEmpty {
            let defaultEndpointName = info.title.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
            dictionary[defaultEndpointName] = operations
            return dictionary
        }

        for tag in tags {
            dictionary[tag] = operations.filter { $0.tags.contains(tag) }
        }
        return dictionary
}
```

**Comment by yonaskolb** [comment]
Hi @dangthaison91 
I would prefer to add a tag key with the name "" (this matches the empty string tag property of a request without a tag). 
You can also change the path of an generated template file by using stencil tags in the `path` property. Feel free to create a PR to change any of this

**Comment by yonaskolb** [comment]
Also the implementation of this should probably handle the case where some operations have tags and some don't. Your example would only work if there are 0 tags

**Comment by dangthaison91** [comment]
@yonaskolb Yes, my code is temporary fix while doing some experiment with your SwagGen to know it work with my custome template for Moya.

**Comment by dangthaison91** [comment]
My first PR for this issue @yonaskolb. Really love that SwagGen is more flexible than original Swagger Codegen. You should update the document to tell others how simplicity, flexible SwagGen is.

We can define default name in our own template instead of hard code in Code Generator.

```yaml
- path: request.swift
  context: tags
  destination: "Sources/Requests/{% if name %}{{ name|upperCamelCase }}{% else %}YOUR_DEFAULT_NAME_HERE{% endif %}.swift"

```

**Comment by yonaskolb** [comment]
Thanks, glad you like it! 😀
