### ISSUE TITLE
Referencing instance method 'encode()' on 'Array'

### ISSUE THREAD

**Issue by keithcml** [yonaskolb/SwagGen#243]
Hi @yonaskolb 

I have an issue on my POST request model.

![image](https://user-images.githubusercontent.com/5032142/81467429-14d4b000-920b-11ea-93b7-c16c10e25f74.png)

There is an error when building the project.

![image](https://user-images.githubusercontent.com/5032142/81467393-e951c580-920a-11ea-87d6-7a603969ae96.png)

**Comment by keithcml** [comment]
sorry, just solve it

**Comment by goors** [comment]
@keithcml  how did you solve this?
