### ISSUE TITLE
Add public initializers to Swagger entities

### ISSUE THREAD

**Issue by Liquidsoul** [yonaskolb/SwagGen#256]
I am using the `Swagger` module in [OpenApiStubGenerator](https://github.com/Liquidsoul/OpenApiStubGenerator) and even if I have managed to work around the scope issue using `@testable import`, I find that it may be interesting to expose public initializers in the module so that one could create entities without relying only on JSON dictionaries.

Do you think this could be interesting to add that @yonaskolb ? I would be happy to submit a PR with this 😊

**Comment by yonaskolb** [comment]
HI @Liquidsoul. Yes, I was there was a way in swift to make the memberwise init public. For what purpose do you require programmatically initializing them? I'm happy if you want to make a PR adding public inits

**Comment by Liquidsoul** [comment]
I am using them in some tests where I need to configure Swagger objects as inputs for different scenarios.

PR incoming then 👍
