### ISSUE TITLE
Not able to build SwagGen locally

### ISSUE THREAD

**Issue by SwapnilSankla** [yonaskolb/SwagGen#3]
I am trying to build SwagGen locally via command line (I have XCode8 installed).
Build is failing with following errors.

`➜  SwagGen git:(master) swift build -c release
Linking CYaml
Compile Swift Module 'JSONUtilities' (8 sources)
Compile Swift Module 'Spectre' (8 sources)
Compile Swift Module 'Yams' (9 sources)
/Users/sankalas/SwapnilSankla-backup/Delta/SwagGen/Packages/Yams-0.2.0/Sources/Yams/Emitter.swift:324:13: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeMutableBytes'
        _ = value.withUnsafeMutableBytes { value in
            ^~~~~ ~~~~~~~~~~~~~~~~~~~~~~
/Users/sankalas/SwapnilSankla-backup/Delta/SwagGen/Packages/Yams-0.2.0/Sources/Yams/Emitter.swift:346:13: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeMutableBytes'
        _ = tag.withUnsafeMutableBytes { tag in
            ^~~ ~~~~~~~~~~~~~~~~~~~~~~
/Users/sankalas/SwapnilSankla-backup/Delta/SwagGen/Packages/Yams-0.2.0/Sources/Yams/Emitter.swift:367:13: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeMutableBytes'
        _ = tag.withUnsafeMutableBytes { tag in
            ^~~ ~~~~~~~~~~~~~~~~~~~~~~
/Users/sankalas/SwapnilSankla-backup/Delta/SwagGen/Packages/Yams-0.2.0/Sources/Yams/Parser.swift:130:9: error: value of type 'ContiguousArray<CChar>' (aka 'ContiguousArray<Int8>') has no member 'withUnsafeBytes'
        utf8CString.withUnsafeBytes { bytes in
        ^~~~~~~~~~~ ~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /Users/sankalas/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/sankalas/SwapnilSankla-backup/Delta/SwagGen/.build/release.yaml`

**Comment by lvdaqian** [comment]
I met the same issue before. You can reference issue #2 .

The main reason is Yams Module use the newest swift version 3.0.1. 

So you just need to update XCode or your swift version.

**Comment by yonaskolb** [comment]
Thanks @lvdaqian
