### ISSUE TITLE
Version 4.7.0 not available on brew due to failed GH Action

### ISSUE THREAD

**Issue by Shaquu** [yonaskolb/SwagGen#307]
Hi, please rerun/fix 4.7.0 release on brew

**Comment by Shaquu** [comment]
@yonaskolb

**Comment by yonaskolb** [comment]
The formula for SwagGen lives in this repo. What is the issue you're running into? If you have a fix could you open a PR here

**Comment by Shaquu** [comment]
Latest version available for brew is 4.6.0
I believe that it not lived in the repo but in the builds somehow which are failing

**Comment by yonaskolb** [comment]
It would be helpful if you had a build error you could share
