### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by daisoreanu** [yonaskolb/SwagGen#311]
Hello, 

I have tried installing using HomeBrew version 3.6.4, swift 5.7 and command line tools 14.0.1.

I am fallowing the next steps:
brew tap yonaskolb/SwagGen https://github.com/yonaskolb/SwagGen.git
brew install SwagGen

And I get the terminal response:

error: xcbuild executable at '/Library/Developer/SharedFrameworks/XCBuild.framework/Versions/A/Support/xcbuild' does not exist or is not executable

**Comment by daisoreanu** [comment]
Also got the next error while trying to install using Mint:

🌱 Resolving package
error: 'github.com_yonaskolb_swaggen': Invalid manifest
/private/var/folders/f2/p_q5bmbx0n32f2k65kh53rm40000gp/T/mint/github.com_yonaskolb_SwagGen/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
🌱 Encountered error during "swift package resolve"
🌱  Failed to resolve SwagGen 4.7.0 with SPM

**Comment by daisoreanu** [comment]
Managed to fix the issue.

The problem was that Swift Package Manger(SPM) was pointing to CommandLineTools, not to Xcode:
/Library/Developer/CommandLineTools

Used this command to find the path:
xcode-select --print-path

And it should be (it may be different on your machine):
/Applications/Xcode.app/Contents/Developer

Update it using:
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

**Comment by daisoreanu** [comment]
Managed to fix the issue.

The problem was that Swift Package Manger(SPM) was pointing to CommandLineTools, not to Xcode:
/Library/Developer/CommandLineTools

Used this command to find the path:
xcode-select --print-path

And it should be (it may be different on your machine):
/Applications/Xcode.app/Contents/Developer

Update it using:
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

**Comment by rigamikhail27** [comment]
Thanks!
