### ISSUE TITLE
Comparison with OpenAPI generator

### ISSUE THREAD

**Issue by grigorye** [yonaskolb/SwagGen#316]
Hi there, I don't see mention of [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator) in alternatives in README, so I wonder how does SwagGen compare to that? They also have support for [Swift 5](https://github.com/OpenAPITools/openapi-generator/tree/131bd4fd35fa512b3841dc3520a78930fdd6bc0d/modules/openapi-generator/src/main/resources/swift5), and have support for custom templates (if I understand that correctly)...

**Comment by yonaskolb** [comment]
I believe it's a fork of https://github.com/swagger-api/swagger-codegen.
I'm not sure what has changed over the years. I'll mention https://github.com/OpenAPITools/openapi-generator in the readme though
