### ISSUE TITLE
is development over?

### ISSUE THREAD

**Issue by mojidabckuu** [yonaskolb/SwagGen#322]
Hey @yonaskolb

I see that readme was edited few hours ago and would like to know the motivation to suspend the development if you don't mind to share :)

`swagger` is widely known on iOS tool to generate the networking. 600+ stars prove it.

**Comment by yonaskolb** [comment]
Hi @mojidabckuu, it's a good question.
I saw apple announced their open api generator https://github.com/apple/swift-openapi-generator during WWDC, and it made me think about if I still want to work on this. I just haven't had the energy or interest to work on it lately. I have so many other side projects that take my time. SwagGen hasn't had a release in over a year. I'm still happy to push out the occasional fix, but I can't imagine it will see much development. But as with everything open source you are free to fork and edit as you please.
If there's a big response to this from the community, or anyone wanted to fund it may make me reconsider.
