### ISSUE TITLE
Is it possible to write out the type without ? to mark it optional?

### ISSUE THREAD

**Issue by sebbu** [yonaskolb/SwagGen#34]
I have the requirement to generate the type of a property without the optional mark (?).

Should I just update func getValueContext and extend it, i.e with

    ....
    "optionalType": getValueType(value) + (value.required ? "" : "?"),
    "type": getValueType(value),

**Comment by yonaskolb** [comment]
Hi @Sebbu. The type without the optional is already mapped to `type` actually, so you can just change what you need in the template

**Comment by sebbu** [comment]
Thanks a lot for the fast reply and the easy solution. Is it documented? Did I not read well? Or can I help with documentation?

**Comment by yonaskolb** [comment]
The available properties available in a Swift template aren't documented at the moment. I hadn't until now, as it's been a little bit in flux before a 1.0 release. But the properties are pretty stable stable now if you'd like to help. 
All the properties are generated in CodeFormatter and SwiftFormatter

**Comment by yonaskolb** [comment]
Closing this now. Let me know if you have any other questions
