### ISSUE TITLE
Readme examples

### ISSUE THREAD

**Issue by nitrag** [yonaskolb/SwagGen#35]
Can we get some examples added to readme to kickstart using this? How to make an API request, specify parameters and return a User model perhaps?

**Comment by yonaskolb** [comment]
Yeah, I've been meaning to do that. Both a readme for the swift template and readme for the generated swift project.

For a short summary, each Request lives under `MyApiName.MyTag.MyOperationId.Request`. Each request can be initialised with it's parameters (optional params are optional). Then just call `makeRequest(complete:)` on that object. The completion handler will return an `ApiResponse` that will have a `result` property which contains the typed decoded response or an error.
To change the base url used, change it in `ApiClient.default.baseURL` as that's what is used under the hood.

If wanting more control over requests, use `ApiClient` directly (either default or your own instance) and make a request with apiClient.makeRequest()

**Comment by mihirpmehta** [comment]
Overall i get the idea how to use it but a short example on readme would be much helpful 

Thanks

**Comment by yonaskolb** [comment]
Added in #87 and released in 2.1.2
