### ISSUE TITLE
Switch statement must have at least...

### ISSUE THREAD

**Issue by nitrag** [yonaskolb/SwagGen#37]
```
'switch' statement body must have at least one 'case' or 'default' block
```

ActivateCreate.swift
```swift
extension API.Auth { 
....
public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Void

            public var success: Void? {
                switch self {
                }
            }
```

**Comment by yonaskolb** [comment]
Hi Nitrag
What does your operation spec look like. It might be that your operation spec is missing a `responses` field?
From the Swagger spec, each operation requires at least one defined response https://swagger.io/specification/#responses-object-54
Does that answer your issue?

Reminds me that I should add a step before generating that lints the spec.

**Comment by nitrag** [comment]
Yea you're probably right. The API isn't complete, barely started really.
I'll check back in a bit when it's a little more developed.

**Comment by yonaskolb** [comment]
Ok, then closing this now. Let me know if you have any other issues
