### ISSUE TITLE
Add downstream changes

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/SwagGen#45]
Hi @Liquidsoul, I've noticed you've made some useful changes in your fork. Would you be open to submitting some of the general ones back into this repo via one or more PR's?

**Comment by Liquidsoul** [comment]
Hi @yonaskolb !
I'll try to see what I can do ;)

**Comment by Liquidsoul** [comment]
I suppose that what interest you most is the handling of [inline schemas](https://github.com/Liquidsoul/SwagGen/commit/dea3f5218124b72adfdeb7321a818f1f1ae0d001)?
As stated in the commit, this may not be fully ready for a PR and may need some more work.
Nevertheless, it's working in our use case with some custom templates 👍
