### ISSUE TITLE
Update to OpenAPI 3

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/SwagGen#47]
Update the swagger spec to 3.0 https://swagger.io/specification/

Maybe also rename the repo to make reference to OpenAPI? Any name suggestions?

**Comment by zdnk** [comment]
Any update on support for OpenAPI 3?

**Comment by yonaskolb** [comment]
Not at this time. All of the projects I use SwagGen with are using the 2.0 spec, so the motivation is low to update it. If I had more time I would work on it

**Comment by yonaskolb** [comment]
The company I'm at is going to update to Swagger 3.0 soon, so looks like this will happen in the next couple of months

**Comment by CVertex** [comment]
👍 Hey Yonas, can't wait to see this!

**Comment by yonaskolb** [comment]
Hi guys, sorry for the delay on this. We’re upgrading at work, so I’ll work on this next week!

**Comment by yonaskolb** [comment]
Made some good progress today 👍

**Comment by yonaskolb** [comment]
PR is here if you guys want to give it a spin on your specs and report back https://github.com/yonaskolb/SwagGen/pull/118
