### ISSUE TITLE
Use StencilSwiftKit instead of Stencil

### ISSUE THREAD

**Issue by Liquidsoul** [yonaskolb/SwagGen#48]
I use stencils in [`Sourcery`](https://github.com/krzysztofzablocki/Sourcery) and [`Swiftgen`](https://github.com/SwiftGen/SwiftGen) and I miss some nice additions from [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit).
It would be really cool if SwagGen could use it. This would introduce some nice additions for custom templates like `macro`, `set` and some nice string `filters`.

I saw that you use your own version of `Stencil` to add some feature to the  `include` node. It may not be feasible but this is at least for your information in case you did not know it existed 😉

**Comment by yonaskolb** [comment]
Yeah, I'd be up for linking to StencilSwiftKit. As you say though I've added some non compatible customizations to Stencil.
The line escaping would need to be added to Stencil, via my PR or probably this one https://github.com/kylef/Stencil/pull/92
Once that's done I can move my `include` changes into a new tag if it won't get merged

**Comment by yonaskolb** [comment]
Once https://github.com/kylef/Stencil/pull/214 is merged and SwiftStencilKit uses it in a new release we can move to `SwiftStencilKit`.
A few of us are seeing if we can get access the Stencil repo or make a hard fork of it to speed up updates https://github.com/krzysztofzablocki/Sourcery/issues/567

**Comment by yonaskolb** [comment]
Implemented in #111
