### ISSUE TITLE
Not return allProperties

### ISSUE THREAD

**Issue by dangthaison91** [yonaskolb/SwagGen#52]
Seem that, current generator didn't return all model's properties as expected. When I user `allProperties` it return `parentProperties` only:

**Expected:** 
```swift
context["allProperties"] = schema.properties.map(getPropertyContext) + schema.parentProperties.map(getPropertyContext)
```
**Actual:** 
```swift
context["allProperties"] = schema.parentProperties.map(getPropertyContext)
```

**Comment by yonaskolb** [comment]
It does actually return all the properties. `parentProperties` is perhaps quite a misleading name. It is actually a property that returns a model's own properties and all those of it's parents, as can be seen here

```
    var parentProperties: [Property] {
        return parentRequiredProperties + parentOptionalProperties
    }

    private var parentRequiredProperties: [Property] {
        return (parent?.value.parentRequiredProperties ?? []) + requiredProperties
    }

    private var parentOptionalProperties: [Property] {
        return (parent?.value.parentOptionalProperties ?? []) + optionalProperties
    }
```
That getter should probably be renamed.

**Comment by yonaskolb** [comment]
Closing this for now. Let me know if you are seeing expected properties not being returned here
