### ISSUE TITLE
Bundle templates

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/SwagGen#55]
Bundle the templates when installing and allow those templates as a default template for a language.
So instead of passing `--template Templates/Swift/template.yml` you can pass `--language swift`

**Comment by mackoj** [comment]
Does this means that in the future you plan to provide template for various languages? Like Kotlin?

**Comment by yonaskolb** [comment]
It's definitely possible to have a template for another language. I don't think I'll be creating any others myself for now, but feel free to contribute one!
