### ISSUE TITLE
Logo Design: SwagGen

### ISSUE THREAD

**Issue by baranpirincal** [yonaskolb/SwagGen#70]
Hey, I examined your project and realized that your project has no logo design yet. What do you think about it? If you interested I can contribute on your project with making logo design. Actually  my main aims are supporting open source projects and make my portfolio better. I am waiting your feedback and if you have an idea we can talk about design decisions. Have a nice day! :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by yonaskolb** [comment]
Hi @baranpirincal, sounds great.
I had considered a logo when I started the project. The tricky thing is that the repo is called SwagGen as it uses Swagger. But Swagger has now been renamed to OpenApiSpec, so not sure which one it should aim for

**Comment by baranpirincal** [comment]
@yonaskolb I am not sure but in my opinion, if the basement of your project changed or renamed you must rename your project too. Because, as I understand , there is no repository called 'swagger' anymore.
