### ISSUE TITLE
Prefix support for model filenames and class name

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/SwagGen#73]
Hi,

Thanks for `SwagGen`.

I would love to be able to add prefix or suffix to model filename and model class name.
I'm willing to implementing it. How can I do it ?

Thanks,

**Comment by yonaskolb** [comment]
Hi @mackoj 

Thanks for offering to help. I actually had some related in-progress work there so I've added it for you in #75

**Comment by mackoj** [comment]
Thanks @yonaskolb
