### ISSUE TITLE
Custom URL Class in APIClient

### ISSUE THREAD

**Issue by sandronoel** [yonaskolb/SwagGen#83]
A custom URL class that completely overrides but does not inherit from the Swift URL class
making line 145 of the APICLient class 
`let url = URL(string: "\(baseURL)\(path)")!`
not compile.

also the isEqual(to:) of the classModelAndView.swift
`guard self.modelMap == object.modelMap else { return false }`
has an error "Expression type 'Bool' is ambiguous without more context"

is it a setting I forgot?

**Comment by yonaskolb** [comment]
Are you saying that you have a definition called `URL` as well? That should probably be renamed, as you will get errors in lots of places if you use it, as it will always conflict with `Swift.URL`.

Also what is the type of `modelMap`?

**Comment by sandronoel** [comment]
Oh for @%$# sakes. they do have a definition called URL - where is that icon where one slaps forehead ?, I apologize.
