### ISSUE TITLE
Question: Generated Code Structure and logic

### ISSUE THREAD

**Issue by sandronoel** [yonaskolb/SwagGen#86]
Hi, after the code is generated, where do I start using it?
There is no clear path to start using the API generated with your tool, could you possibly explain the generated architecture and logic of calls to the back end?

a sample would be greatly appreciated.

Regards.

**Comment by sandronoel** [comment]
no, nothing?

**Comment by sandronoel** [comment]
I saw Request #35 was asking for the same, though the explanation is appreciated, a sample code would be helpful.

**Comment by yonaskolb** [comment]
Added in #87 and released in 2.1.2
