### ISSUE TITLE
Type name overrides

### ISSUE THREAD

**Issue by yonaskolb** [yonaskolb/SwagGen#90]
The template options can provide some dictionaries to override model or request type names

**Comment by cerupcat** [comment]
I have a 2 requests with the same name. 1 request requires parameters and another doesn't. The generated file names are the same and that's causing an issue of only 1 of the requests to be seen by the compiler.

Any ways around that?

Example:

```
/v1/user (fetches all users)
/v1/user/{id} (fetches specific user by id)
```
